    > python3 main.py
    √ cube(3) == 27
    √ Called cube(2, 3), Caught expected exception. TypeError: cube() takes 1 positional argument but 2 were given
    X Called cube(10), expected TypeError, Got 1000 instead.
    X Called cube([]), expected ZeroDivisionError, Caught unexpected exception. TypeError: can't multiply sequence by non-int of type 'list'
    X Called cube('a'), expected 1000, Caught unexpected exception. TypeError: can't multiply sequence by non-int of type 'str'
    X cube(2) != 0.125. Got 8 instead.
    1000
